{{- if and (not .Values.disableTls) (not .Values.useClientCertificate) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: certificate-issuer
spec:
  acme:
    email: supervision@datagalaxy.com
    privateKeySecretRef:
      name: letsencrypt-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: kong
{{- end }}