{{- if .Values.useClientCertificate }}
{{- with .Values.clientCertificate  }}
apiVersion: v1
data:
  tls.crt: {{- toYaml .certificate | indent 4 }}
  tls.key: {{- toYaml .key         | indent 4 }}
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .secretName }}
{{- end }}
{{- end }}