{{- if .Values.global.datagalaxyRegistry }}
apiVersion: "v1"
data:
  {{- with .Values.global.datagalaxyRegistry }}
  .dockerconfigjson: "{{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .server .username .password (printf "%s:%s" .username .password | b64enc) | b64enc }}"
  {{- end }}
kind: "Secret"
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  name: "datagalaxy-registry"
type: "kubernetes.io/dockerconfigjson"
{{- end }}