apiVersion: v2
dependencies:
- condition: connectivity-api.enabled
  name: connectivity-api
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.1.5
- condition: connector-server.enabled
  name: connector-server
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.1
- condition: datascienceapi.enabled
  name: datascienceapi
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.0
- alias: elasticsearch-a
  condition: elasticsearch-a.enabled
  name: elasticsearch
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.3.0
- alias: elasticsearch-b
  condition: elasticsearch-b.enabled
  name: elasticsearch
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.3.0
- condition: hubservice.enabled
  name: hubservice
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.0
- condition: logstash.enabled
  name: logstash
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.0-7.9.2
- condition: minio.enabled
  name: minio
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.0-8.0.0
- condition: publicapi.enabled
  name: publicapi
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.1.1
- condition: sqlserver.enabled
  name: sqlserver
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.3.0
- condition: vault.enabled
  name: vault
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.0.1-0.12.0
- condition: webclient.enabled
  name: webclient
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.1.1
- condition: webservices.enabled
  name: webservices
  repository: oci://datagalaxy.azurecr.io/platform/helm
  version: 1.1.4
name: platform
version: 1.15.7
