{{- if .Values.vault.initData }}
apiVersion: "v1"
kind: "Secret"
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
  name: "vault-init-data"
stringData:
  {{- with .Values.vault.initData }}
  rootToken:  {{ .rootToken }}
  unsealKey0: {{ .unsealKey0 }}
  unsealKey1: {{ .unsealKey1 }}
  unsealKey2: {{ .unsealKey2 }}
  unsealKey3: {{ .unsealKey3 }}
  unsealKey4: {{ .unsealKey4 }}
  {{- end }}
{{- end }}