{{- if .Values.clientCertificate }}
apiVersion: v1
data:
  {{- with .Values.clientCertificate }}
  tls.crt: {{- toYaml .certificate | indent 4 }}
  tls.key: {{- toYaml .key         | indent 4 }}
  {{- end }}
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: client-certificate
{{- end }}